Detal out
idaholab/TEAL pull request #33
Opened 2021-10-01 20:02 UTC by worseliz

--------
Pull Request Description
--------
##### What issue does this change request address?
Produces detailed cashflow output.

##### What are the significant changes in functionality due to this change request?
More data can be visualized from TEAL.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-10-01 20:03 UTC, worseliz commented
I realized I did this on my user manual branch. I tried deleting the files but they're still showing up here even though they are not in my local branch.

2021-10-01 20:42 UTC, PaulTalbot-INL requested changes
A few notes to look at; I did not carefully review the documentation changes yet.

2021-10-01 20:42 UTC, PaulTalbot-INL commented on src/CashFlow_ExtMod.py
> +    print(metrics.items())
may want to take this print out

2021-10-01 20:42 UTC, PaulTalbot-INL commented on src/CashFlows.py
> +    self._outputtype = None
this should probably be camel back, as `self._outputType`. Appears in several places.

2021-10-01 20:42 UTC, PaulTalbot-INL commented on src/main.py
> +  print(lifeCashflow)
this print can be removed

2021-10-01 20:42 UTC, PaulTalbot-INL commented on src/main.py
> +  #print("\n\n\n",compCashflows.keys())
print comments in this file should be removed

2021-10-01 20:42 UTC, PaulTalbot-INL commented on tests/CashFlow_test_Output.xml
> +    <name>CashFlow_test_IRR</name>
if this is a new test, update the TestInfo and remove the revisions

2021-10-01 20:43 UTC, PaulTalbot-INL commented
I think this branch might need "devel" merged into it to resolve conflicts and catch up some doc changes.

2021-10-12 16:11 UTC, PaulTalbot-INL requested changes
A few cleanup changes

2021-10-12 16:11 UTC, PaulTalbot-INL commented on src/CashFlow_ExtMod.py
> +    #print("\n\n\n\n\n",globalSettings)
this line can be removed, I suspect

2021-10-12 16:11 UTC, PaulTalbot-INL commented on src/CashFlow_ExtMod.py
> +          for k, v in metrics.items():
there's a few too many spaces in this tab

2021-10-12 16:11 UTC, PaulTalbot-INL commented on src/CashFlows.py
> +    Get output Type
these docstring lines should be tabbed in 2 spaces, 1 indent in from the triple-quotes

2021-10-12 16:11 UTC, PaulTalbot-INL commented on src/main.py
> +  OutputType = settings.getOutput()
I think `OutputType` should be `outputType` technically. I don't make these rules.

2021-10-12 16:29 UTC, PaulTalbot-INL approved these changes

2021-10-12 16:29 UTC, PaulTalbot-INL commented
Approved for merge when tests pass, if no further changes needed.

2021-10-12 16:33 UTC, merged