Changed handling of recurring cashflows to better suit object oriented
idaholab/TEAL pull request #59
Opened 2022-07-13 22:32 UTC by AnthoneyGriffith

--------
Pull Request Description
--------
##### What issue does this change request address?
#58 

##### What are the significant changes in functionality due to this change request?
When defining cashflows outside of TEAL, calculateYearlyCashflow/calculateIntraYearlyCashflow over the project lifetimes. TEAL will now consider a unique cashflow expression for each year of the project life.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-07-14 14:28 UTC, PaulTalbot-INL commented
@dylanjm do you have time to double-check this fix? I want to make sure we didn't overlook something.

2022-07-14 15:00 UTC, dylanjm commented
> @dylanjm do you have time to double-check this fix? I want to make sure we didn't overlook something.

@PaulTalbot-INL Yes, I can check it today.

2022-07-14 18:31 UTC, dylanjm requested changes

2022-07-14 18:31 UTC, dylanjm commented on src/CashFlows.py
> +          elif len(value) > 1 and len(value) < t or len(value) > t:
I think it would be more readable to use chained equality operators here:

```python
elif 1 < len(value) < t or len(value) > t
```

2022-07-14 18:31 UTC, dylanjm commented on src/CashFlows.py
> +          # alpha and driver arrays should be the same length as the project length
Can you expound on this comment, please? Your conditional doesn't seem to satisfy this comment.

2022-07-14 18:31 UTC, dylanjm commented on src/CashFlows.py
> +                relativeIndex = 1
The variable names in this block could be improved to be more descriptive. 

I believe this whole block could be refactored into something a little more succinct and readable. You'll need to add `itertools` module up top:

```python
import itertools as it # (put at top of file)
elif 1 < len(value) < t or len(value) > t:
  listArray = np.zeros(t)
  # NOTE: this iterator will never exhaust itself so don't try to access with a specific state later
  repeating_values = it.cycle(value[1:])
  listArray[1:] = [next(repeating_values) for _ in listArray[1:]] # or list(map(lambda _: next(repeating_values), listArray[1:]))
toExtend[name] = listArray
```

2022-07-14 18:31 UTC, dylanjm commented on src/main.py
> +  #        to operatingMask = np.logical_and(years >= start, years < end)
I think this block of comments can be removed. Also please change comments from describing the code to the motivation behind the code.

2022-07-14 18:31 UTC, dylanjm commented on src/main.py
> +  relativeOperatingYears = operatingYears - start # This is relative component startup year
I think the comment could be removed if we change the variable name to `relativeStartupYear` and perhaps we can add a comment about why we care about this number.

2022-07-14 18:31 UTC, dylanjm commented on src/main.py
> +  # Handling inflation and tax rates for the project based on how many years into the project
This comment can probably be reduced or expounded upon. I am more curious about why we are raising something to the negative power here. Can you add a comment expounding on this?

2022-07-14 18:31 UTC, dylanjm commented on tests/PyomoTest.py
> +    @ In, projectlife, int, length of project
What's the purpose of changing this functionality when previously we were able to get `projectlife` by running `comp.getLifetime()`?

2022-07-14 19:05 UTC, AnthoneyGriffith commented on src/CashFlows.py
> +                relativeIndex = 1
This alternative worked well. Thank you!

2022-07-14 19:51 UTC, dylanjm commented on src/CashFlows.py
> +import itertools as iter
I wouldn't call this `iter` as `iter()` is a built-in function.  I typically call it `it` or `itools`

2022-07-14 19:52 UTC, dylanjm commented on src/CashFlows.py
> +###
These are not needed.

2022-07-14 20:22 UTC, dylanjm commented on src/CashFlows.py
> +            listArray[1:] = [next(repeatingValues) for _ in listArray[1:]]
Is there a better variable name we can give this?

2022-07-14 20:24 UTC, dylanjm requested changes
Just minor changes this time.

2022-07-20 16:01 UTC, PaulTalbot-INL commented
@dylanjm @AnthoneyGriffith checking on this PR, any additional changes or reviews needed?

2022-07-20 16:38 UTC, dylanjm approved these changes
All changes look good. No additional feedback.

2022-07-20 16:38 UTC, merged